version: '3'

services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_production
    ports:
      - "3307:3306"
    networks:
      - backend
    volumes:
      - ./files:/tmp/files
      - ./docker:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-padmin"]
      interval: 5s
      timeout: 15s
      retries: 5

  # Flask server service
  flask-app:
    build: .
    container_name: flask-container
    environment:
      - FLASK_APP=server.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - SQLALCHEMY_DATABASE_URI=mysql://root:admin@mysql/db_production
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
